import { PolicyConfigItem, PliPolicy } from '../../lib/pli/types';

export const POLICY_REGISTRY: Record<PliPolicy, PolicyConfigItem> = {
  SURAKSHA: {
    name: 'Whole Life Assurance (Suraksha)',
    code: 'WLA',
    bonusRate: 76,
    minSumAssured: 20000,
    maxSumAssured: 5000000,
    minAge: 19,
    maxAge: 55,
    minTerm: 5,
    maxTerm: 60,
    loanYears: 4,
    surrenderYears: 3,
    presetMaturityAges: [55, 58, 60],
    description: 'Assures payment of sum assured plus bonus upon attaining age 80 or earlier death.',
  },
  SANTOSH: {
    name: 'Endowment Assurance (Santosh)',
    code: 'EA',
    bonusRate: 52,
    minSumAssured: 20000,
    maxSumAssured: 5000000,
    minAge: 19,
    maxAge: 55,
    minTerm: 5,
    maxTerm: 55,
    loanYears: 3,
    surrenderYears: 3,
    presetMaturityAges: [35, 40, 45, 50, 55, 58, 60],
    description: 'Provides sum assured with accrued bonus at maturity or to nominee upon death.',
  },
  SUVIDHA: {
    name: 'Convertible Whole Life Assurance (Suvidha)',
    code: 'CWLA',
    bonusRate: 76,
    minSumAssured: 20000,
    maxSumAssured: 5000000,
    minAge: 19,
    maxAge: 50,
    minTerm: 5,
    maxTerm: 55,
    loanYears: 4,
    surrenderYears: 3,
    presetMaturityAges: [35, 40, 45, 50, 55, 58, 60],
    description: 'Whole Life policy convertible into Endowment Assurance after 5 years.',
  },
  SUMANGAL: {
    name: 'Anticipated Endowment Assurance (Sumangal)',
    code: 'AEA',
    bonusRate: 48,
    minSumAssured: 20000,
    maxSumAssured: 5000000,
    minAge: 19,
    maxAge: 45,
    minTerm: 15,
    maxTerm: 20,
    loanYears: null, // No loan facility available for Sumangal
    surrenderYears: 3,
    description: 'Money back policy providing periodic survival benefits and full maturity benefits.',
  },
  YUGAL_SURAKSHA: {
    name: 'Joint Life Assurance (Yugal Suraksha)',
    code: 'JLEA',
    bonusRate: 52,
    minSumAssured: 20000,
    maxSumAssured: 5000000,
    minAge: 19,
    maxAge: 45,
    minTerm: 5,
    maxTerm: 45,
    loanYears: 3,
    surrenderYears: 3,
    presetMaturityAges: [35, 40, 45, 50, 55, 58, 60],
    description: 'Joint life cover for couples where both lives are covered under a single policy.',
  },
  BAL_JEEVAN_BIMA: {
    name: 'Children Policy (Bal Jeevan Bima)',
    code: 'CHILDREN',
    bonusRate: 52,
    minSumAssured: 20000,
    maxSumAssured: 300000, // Max ₹3 Lakhs (or equal to parent's SA)
    minAge: 5,
    maxAge: 20, // Child entry age 5 to 20 years
    minTerm: 5,
    maxTerm: 20,
    loanYears: null, // No loan facility available
    surrenderYears: null, // No surrender option (Paid-Up after 5 years)
    description: 'Provides insurance cover for children of PLI policyholders with premium waiver benefit.',
  },
};
