import { POLICY_REGISTRY } from '../../config/pli/policies';
import { PolicyConfigItem } from './types';

export const REFERENCE_AGE = 19;
export const DEFAULT_AGE_RATE = 0.025;
export const STANDARD_REBATE = 5;
export const JOINT_LIFE_REBATE = 7;
export const DEFAULT_GST_RATE = 0;
export const CALCULATION_VERSION = '2.0';

export const MIN_PREMIUM_BOUND = 100;
export const MAX_PREMIUM_BOUND = 100000;

export const POLICY_CONFIG: Record<string, PolicyConfigItem> = {
  // Canonical Policy Keys
  SURAKSHA: POLICY_REGISTRY.SURAKSHA,
  SANTOSH: POLICY_REGISTRY.SANTOSH,
  SUVIDHA: POLICY_REGISTRY.SUVIDHA,
  SUMANGAL: POLICY_REGISTRY.SUMANGAL,
  YUGAL_SURAKSHA: POLICY_REGISTRY.YUGAL_SURAKSHA,
  BAL_JEEVAN_BIMA: POLICY_REGISTRY.BAL_JEEVAN_BIMA,

  // Legacy Policy Key Aliases
  WHOLE_LIFE: POLICY_REGISTRY.SURAKSHA,
  ENDOWMENT: POLICY_REGISTRY.SANTOSH,
  CONVERTIBLE_WHOLE_LIFE: POLICY_REGISTRY.SUVIDHA,
  ANTICIPATED_ENDOWMENT: POLICY_REGISTRY.SUMANGAL,
  JOINT_LIFE: POLICY_REGISTRY.YUGAL_SURAKSHA,
  CHILDREN: POLICY_REGISTRY.BAL_JEEVAN_BIMA,
};
